### ISSUE TITLE
I place the file in, click enter... gone.

### ISSUE THREAD

**Issue by Scrut1ny** [EscaLag/Abobus-obfuscator#1]
Program launches, but when it gets to placing the file into the py program it just closes when you click enter. The obfuscated file is no where to be found. idk whats going on.

Heres the output / error.
![rsGBA5ZJ5Z](https://user-images.githubusercontent.com/53458032/196541025-4252fe0a-ceec-4d8e-83cb-d6f45808366f.png)

**Comment by Its-sl** [comment]
I think this is also for obfuscation of function names, try replacing the function name with something long so that there are more than 3 characters

**Comment by EscaLag** [comment]
> I think this is also for obfuscation of function names, try replacing the function name with something long so that there are more than 3 characters

yes, you are completely right. I'll try to fix it in the next patch.

**Comment by Scrut1ny** [comment]
The batch files I write are complex, and I was wandering if it obfuscated ANSI sequences correctly. Also, when will this update come out? xD

![image](https://user-images.githubusercontent.com/53458032/197123350-7389026e-d841-4e52-8981-25338b06bb00.png)

**Comment by EscaLag** [comment]
> The batch files I write are complex, and I was wandering if it obfuscated ANSI sequences correctly. Also, when will this update come out? xD
> 
> ![image](https://user-images.githubusercontent.com/53458032/197123350-7389026e-d841-4e52-8981-25338b06bb00.png)

I am working to ensure that such type of bat files are supported, and work as correctly as possible. Expect a new update soon!

**Comment by Scrut1ny** [comment]
I'm excited, I'll be waiting to try it out!
